const groq = require("./groqClient");
const {
  getWardenSummaryTool,
  getLatestRoomReadings,
  getActiveWardenAlerts,
  getInspectionRooms,
  getWeeklyPattern,
  getWardenAnomalySummary,
  getWardenForecastSummary,
  getWardenDataRangeTool,
  getVisualExplanationContext
} = require("./wardenChatTools");

const TOOL_IMPL = {
  get_warden_summary: getWardenSummaryTool,
  get_warden_room_status: getLatestRoomReadings,
  get_warden_active_alerts: getActiveWardenAlerts,
  get_warden_inspection_rooms: getInspectionRooms,
  get_warden_weekly_pattern: getWeeklyPattern,
  get_warden_anomalies: getWardenAnomalySummary,
  get_warden_forecast: getWardenForecastSummary,
  get_warden_data_range: getWardenDataRangeTool,
  get_visual_explanation_context: getVisualExplanationContext
};

const roomIdParam = {
  type: "string",
  description: 'Room id like "A101" or "All"'
};

const TOOLS = [
  {
    type: "function",
    function: {
      name: "get_warden_summary",
      description: "Get Warden KPI summary including occupancy, inspection rooms, open doors, and active ML alerts.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_room_status",
      description: "Get latest room monitoring data from MongoDB sensor readings for the Warden dashboard.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_active_alerts",
      description: "Get active Warden ML alerts generated by IsolationForest output.",
      parameters: { type: "object", properties: { roomId: roomIdParam, limit: { type: "number" } } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_inspection_rooms",
      description: "Get rooms that need Warden or cleaning inspection based on real sensor state and ML alert evidence.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_weekly_pattern",
      description: "Get Monday to Sunday Warden KMeans behavior pattern discovery rows.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_anomalies",
      description: "Get Warden anomaly/outlier records produced by IsolationForest.",
      parameters: { type: "object", properties: { roomId: roomIdParam, limit: { type: "number" } } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_forecast",
      description: "Get Warden temporal forecasts generated by Prophet or RandomForest regression.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_warden_data_range",
      description: "Get Warden data coverage and validity information for MongoDB sensor/summary records.",
      parameters: { type: "object", properties: { roomId: roomIdParam } }
    }
  },
  {
    type: "function",
    function: {
      name: "get_visual_explanation_context",
      description: "Get currently selected visual context from the dashboard for explanation.",
      parameters: {
        type: "object",
        properties: {
          visualId: { type: "string" },
          visualTitle: { type: "string" }
        }
      }
    }
  }
];

function systemPrompt() {
  return `
You are a Smart Hostel visual analytics assistant for the WARDEN role.

You help the Warden with daily operations, not owner finance.
Use actual dashboard/MongoDB data through tools whenever values are needed.

You must support:
1. Active alert questions
2. Room inspection and cleaning-priority questions
3. Weekly KMeans pattern explanations
4. IsolationForest anomaly explanations
5. Forecast explanations
6. Guidance on what dashboard visual to check next
7. Decision-oriented questions such as which room needs action first

Rules:
- Never invent values.
- Mention the model source when relevant: IsolationForest, KMeans, Prophet, or RandomForestRegressor.
- Explain why the result matters for Warden decisions: inspection, warnings, reporting, cleaning, or manual-check reduction.
- Use short, clear operational language.
- Only include ACTION lines when the user explicitly asks to open, switch, go to, or show a room/floor.
`;
}

function cleanupParsedArgs(parsedArgs) {
  const cleaned = { ...parsedArgs };
  Object.keys(cleaned).forEach((key) => {
    if (cleaned[key] === "" || cleaned[key] === null) delete cleaned[key];
  });
  return cleaned;
}

function userExplicitlyWantsNavigation(message = "") {
  const text = String(message).toLowerCase();
  return (
    text.includes("open ") ||
    text.includes("go to ") ||
    text.includes("switch to ") ||
    text.includes("take me to ") ||
    text.includes("show me ")
  );
}

function normalizeRoomId(value) {
  if (!value || value === "all") return "All";
  return value;
}

async function generateWardenReply({ message, dashboardState }) {
  const roomId = normalizeRoomId(dashboardState?.roomId || dashboardState?.selectedFilters?.roomId || "All");
  const floorId = dashboardState?.floorId || dashboardState?.selectedFilters?.floorId || "All";
  const selectedVisual = dashboardState?.selectedVisual || null;

  const messages = [
    { role: "system", content: systemPrompt() },
    {
      role: "user",
      content: `Current dashboard state:\nfloorId=${floorId}\nroomId=${roomId}\nselectedVisual=${selectedVisual?.title || "none"}\n\nUser question:\n${message}`
    }
  ];

  const firstResponse = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    temperature: 0.1,
    messages,
    tools: TOOLS,
    tool_choice: "auto"
  });

  const assistantMessage = firstResponse.choices?.[0]?.message;

  if (!assistantMessage) {
    return { reply: "Sorry, I could not generate a Warden response just now.", context_used: {} };
  }

  if (!assistantMessage.tool_calls || assistantMessage.tool_calls.length === 0) {
    return { reply: assistantMessage.content || "Sorry, I could not generate a Warden response just now.", context_used: {} };
  }

  messages.push(assistantMessage);
  const toolResults = {};

  for (const toolCall of assistantMessage.tool_calls) {
    const toolName = toolCall.function.name;
    const rawArgs = toolCall.function.arguments || "{}";

    let parsedArgs = {};
    try {
      parsedArgs = JSON.parse(rawArgs);
    } catch {
      parsedArgs = {};
    }

    parsedArgs = cleanupParsedArgs(parsedArgs);

    if (!parsedArgs.roomId && toolName !== "get_visual_explanation_context") {
      parsedArgs.roomId = roomId;
    }

    if (toolName === "get_visual_explanation_context") {
      if (!parsedArgs.visualId && selectedVisual?.id) parsedArgs.visualId = selectedVisual.id;
      if (!parsedArgs.visualTitle && selectedVisual?.title) parsedArgs.visualTitle = selectedVisual.title;
      parsedArgs.dashboardState = dashboardState;
    }

    const impl = TOOL_IMPL[toolName];
    if (!impl) continue;

    const result = await impl(parsedArgs);
    toolResults[toolName] = result;

    messages.push({
      role: "tool",
      tool_call_id: toolCall.id,
      content: JSON.stringify(result)
    });
  }

  messages.push({
    role: "system",
    content: userExplicitlyWantsNavigation(message)
      ? "The user explicitly wants navigation if relevant. You may include ACTION lines if useful."
      : "The user did not explicitly ask for navigation. Do not include ACTION lines."
  });

  const finalResponse = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    temperature: 0.25,
    messages
  });

  return {
    reply: finalResponse.choices?.[0]?.message?.content || "Sorry, I could not generate a Warden response just now.",
    context_used: toolResults
  };
}

module.exports = { generateWardenReply };
